### PR TITLE
Feature/attribute list checker

### PR DESCRIPTION
**Pull request by BaptisteCecconi**
I propose to use a decorator to check the attribute list values. This is implemented with `@attribute_list_checker` in `calculation.py`. I applied the decorator to all the `@SetterProperty` decorated methods, which could be processed this way. I also updated the `vars.py` file and its set of imported variables in `calculation.py` for this new decorator to work well.

### CODE REVIEW

**Comment by BaptisteCecconi** [comment]
The linter error is related to my decorator implementation, which uses an `eval()` function to produce the capital letter variables imported from `vars.py`. If I don't import them, it doesn't work. If I want to solve this error, I can move the `attribute_list_checker` decorator function into `vars.py`, and that should do it.

**Comment by BaptisteCecconi** [comment]
I finally changed gears, and added a `get_var()` function to `vars.py`, similarly to `get_type()` in `types.py`. This solves the problems, and doesn't require to use `eval()` anymore.

**Comment by seignovert** [comment]
This might be superseded by #6, right?
If not, we should merge #6 first and rebased from it.

**Comment by BaptisteCecconi** [comment]
ok, let me close this one and focus on #6

**Pull request closed without merging**
