### PR TITLE
ESA WGC entrypoint

### LINKED ISSUE #2: Adding API for 3rd party WGC instance
For a local processing pipeline, we are planning to setup a local instance of WebGeoCalc at Observatoire de Paris. Although that instance would probably not be accessible from the outer internet, we would need to be able to query that API, and so there is a need for a method to set API URL. 

I've checked #1 and I would suggest to pass an API object instance in the `wgc`  keyword of `Calculation()`, rather of the WGC API short name as a string. 

This would then give:

```
from webgeocalc import Calculation
from webgeocalc import WGC_ESA

Calculation(
    wgc = WGC_ESA,
    kernels = 'OPS  --     Rosetta',
    times = '2014-01-01T01:23:45.000',
    calculation_type = 'STATE_VECTOR',
    target = '67P/CHURYUMOV-GERASIMENKO (1969 R1)',
    observer = 'ROSETTA ORBITER',
    reference_frame = '67P/C-G_CK',
    aberration_correction = 'NONE',
    state_representation = 'PLANETOCENTRIC',
).run()

from webgeocalc import Api

WGC_local = Api('https://wgc.obspm.fr/webgeocalc/api')  # NB: fake API URL

Calculation(
    wgc = WGC_local,
    kernels = 'OPS  --     Rosetta',
    times = '2014-01-01T01:23:45.000',
    calculation_type = 'STATE_VECTOR',
    target = '67P/CHURYUMOV-GERASIMENKO (1969 R1)',
    observer = 'ROSETTA ORBITER',
    reference_frame = '67P/C-G_CK',
    aberration_correction = 'NONE',
    state_representation = 'PLANETOCENTRIC',
).run()
```

### PR DESCRIPTION
**Pull request by seignovert**
Extent WGC API calculation query on [ESA WGC server](http://spice.esac.esa.int/webgeocalc/api).

Example:
```python
from webgeocalc import Calculation

Calculation(
    api = 'ESA',
    kernels = 'OPS  --     Rosetta',
    times = '2014-01-01T01:23:45.000',
    calculation_type = 'STATE_VECTOR',
    target = '67P/CHURYUMOV-GERASIMENKO (1969 R1)',
    observer = 'ROSETTA ORBITER',
    reference_frame = '67P/C-G_CK',
    aberration_correction = 'NONE',
    state_representation = 'LATITUDINAL',
).run()
```

## To do:
* [x] Change API URL entrypoint in API
* [x] Add optional `wgc` attribute in `Calculation` to select API entrypoint.
* [x] Update test suite.
* [x] Update documentation.
* [x] Fix ESA API request issue (see below).
* [x] Update Jupyter example.
* [x] Add CLI `--[jpl|esa]` optional attribute.

### CODE REVIEW

**Comment by seignovert** [comment]
**For now, job mostly failed** due to API configuration issue.

Example of not working on the [API interface](http://spice.esac.esa.int/webgeocalc/example/perform-calculation.html):
```json
{
    "kernels": [
        {
            "type": "KERNEL_SET",
            "id": 5
        }
    ],
    "times": [
        "2014-01-01T01: 23: 45.000"
    ],
    "calculationType": "STATE_VECTOR",
    "target": "67P/CHURYUMOV-GERASIMENKO (1969 R1)",
    "observer": "ROSETTA ORBITER",
    "referenceFrame": "67P/C-G_CK",
    "aberrationCorrection": "NONE",
    "stateRepresentation": "PLANETOCENTRIC",
    "timeSystem": "UTC",
    "timeFormat": "CALENDAR"
}
```

Error:
```
No enum constant gov.nasa.arc.pds.spice.shared.StateRepresentation.PLANETOCENTRIC
```

**Comment by BaptisteCecconi** [comment]
Hi benoît, 

for the sake of consistency, I propose to homogenise the API instance names, and rename the default `API` to `WGC_JPL`.

**Comment by seignovert** [comment]
**Query bug fix**

Response from Boris Semenov:
> Your request fails because in order to compute the planetocentric coordinates in the `API STATE_VECTOR` calculation the `stateRepresentation` attribute must be set to `LATITUDINAL`, as specified in the API documentation:

```json
{
    "kernels": [
        {
            "type": "KERNEL_SET",
            "id": 6
        }
    ],
    "times": [
        "2014-01-01T01:23:45.000"
    ],
    "calculationType": "STATE_VECTOR",
    "target": "67P/CHURYUMOV-GERASIMENKO (1969 R1)",
    "observer": "ROSETTA ORBITER",
    "referenceFrame": "67P/C-G_CK",
    "aberrationCorrection": "NONE",
    "stateRepresentation": "LATITUDINAL",
    "timeSystem": "UTC",
    "timeFormat": "CALENDAR"
}
```

now the query works and results as:
```json
{
   "status": "OK",
   "message": "The request was successful.",
    ...
   "rows": [
     [
       "2014-01-01 01:23:45.000000 UTC",
       -4.5904441,
       -39.43153956,
       10514625.76042228,
       -0.00806197,
       7.01746089e-8,
       -0.813433,
       1142.73632133,
       "2014-01-01 01:23:45.000000 UTC",
       35.07301628
     ]
   ]
}
```

**Comment by seignovert** [comment]
Hi @BaptisteCecconi,

Yes. `WGC_JPL` was already implemented in this PR. However, for better clarity, I changed `WGC_JPL`, `WGC_ESA` to `JPL_API`, `ESA_API`. `API` object is kept as the default WGC API (see below).

The `Calculation` argument was also changed from `wgc='ESA'` to `api='ESA'`.

I also included your suggestion to implement 3rd party WGC API directly in the `api` argument. The ideal usage is to provide the `url` of the API but a custom `Api` object is also accepted.
To improve the performances, any new API url is cached as a new `Api` in a `APIs` dictionary (to avoid `/kernel-set` reloading).

```python
from webgeocalc import Calculation

# with keyword (recommanded)
Calculation(api='JPL', **params)
Calculation(api='ESA', **params)

# with 3rd party url (recommanded)
obs_url = 'https://wgc.obspm.fr/webgeocalc/api'

Calculation(api=obs_url, **params)

# 3rd party `Api` (optional)
from webgeocalc import Api

obs_api = Api(obs_url)

Calculation(api=obs_api, **params)

```

By default, if no input `api` is provided, the default `Api` called will fallback on `WGC_URL` from the global environment variable if present. If `WGC_URL` not configured, the fallback will be on the original `JPL_URL`.

This should fix #2.

**Comment by BaptisteCecconi** [comment]
Hi @seignovert 

Thanks, that is indeed fixing #2. I'll happily use this library in my code now :-)

**Comment by seignovert** [comment]
Nice!
I'm still working on the CLI implementation now (and I need to fix some minor updates on the WGC implementation to fix the CI) before merging.
Then I will push that pypi as `1.3`, stay tune!

**Comment by seignovert** [comment]
Closes #2.

**Pull request merged**
